// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5nkZ9RUKM93ADF1IKRg60QzGkuk6-SE',
    appId: '1:27023411763:web:bf0bf0e99ace9ade153146',
    messagingSenderId: '27023411763',
    projectId: 'ngroupe-des-vainqueurs',
    authDomain: 'ngroupe-des-vainqueurs.firebaseapp.com',
    storageBucket: 'ngroupe-des-vainqueurs.appspot.com',
    measurementId: 'G-THETRMPPDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8t57Vkj24NXkaWZbD77PYASd0YiMD4dQ',
    appId: '1:27023411763:android:8a9b6b34935f00c7153146',
    messagingSenderId: '27023411763',
    projectId: 'ngroupe-des-vainqueurs',
    storageBucket: 'ngroupe-des-vainqueurs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7wfmPH25bBkjfJNz9QzS5wDdfkuJuZ8',
    appId: '1:27023411763:ios:85f2a0e813234279153146',
    messagingSenderId: '27023411763',
    projectId: 'ngroupe-des-vainqueurs',
    storageBucket: 'ngroupe-des-vainqueurs.appspot.com',
    iosBundleId: 'com.example.groupeDesVainqueurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs7wfmPH25bBkjfJNz9QzS5wDdfkuJuZ8',
    appId: '1:27023411763:ios:1d4bbc19a64092d2153146',
    messagingSenderId: '27023411763',
    projectId: 'ngroupe-des-vainqueurs',
    storageBucket: 'ngroupe-des-vainqueurs.appspot.com',
    iosBundleId: 'com.example.groupeDesVainqueurs.RunnerTests',
  );
}
